"""Placement: work out how to teach this student before teaching them.

Two parts, in this order:

1. A short adaptive diagnostic drawn from the installed packs. Items are tagged
   with a skill and a difficulty 1-5. It starts in the middle and walks up on a
   correct answer, down on a wrong one, so twelve items locate a student far
   more precisely than twelve fixed ones. Nothing here is generated by a model;
   every item and every answer key comes from the pack.

2. Five preference questions - language, voice, pace, whether they want the
   example before the theory or after, and whether they want extra reading
   support. These set the *shape* of teaching; the diagnostic sets the
   *starting point*.

The result is a learner profile: a mastery estimate per skill, plus a teaching
style. The pedagogy engine reads both.
"""

from __future__ import annotations

import random
from typing import Any

from . import profile as profile_mod
from .grading import grade

START_DIFFICULTY = 3

def preference_questions(available_languages: list[str]) -> list[dict[str, Any]]:
    langs = [
        {"value": "en", "label": "English"},
        {"value": "bem", "label": "Ichibemba (Bemba)"},
        {"value": "loz", "label": "Silozi (Lozi)"},
    ]
    return [
        {
            "id": "language",
            "prompt": "Which language should I teach in?",
            "help": "You can change this later. Course material stays in the language "
                    "it was written in; this sets how I speak to you.",
            "options": [dict(l, available=l["value"] in available_languages) for l in langs],
        },
        {
            "id": "voice",
            "prompt": "Would you like a male or a female voice?",
            "options": [
                {"value": "female", "label": "Female voice"},
                {"value": "male", "label": "Male voice"},
                {"value": "off", "label": "No voice - text only"},
            ],
        },
        {
            "id": "pace",
            "prompt": "When something is new to you, what helps most?",
            "options": [
                {"value": "scaffolded", "label": "Go slowly, in small steps, and check often"},
                {"value": "standard", "label": "A normal pace with regular checks"},
                {"value": "fast", "label": "Give me the idea quickly and let me practise"},
            ],
        },
        {
            "id": "example_first",
            "prompt": "Do you prefer to see a worked example first, or the rule first?",
            "options": [
                {"value": "yes", "label": "Show me an example, then explain the rule"},
                {"value": "no", "label": "Explain the rule, then show me an example"},
            ],
        },
        {
            "id": "reading_support",
            "prompt": "Would you like extra help with long or technical English?",
            "help": "If you say yes, I define technical words the first time they appear "
                    "and keep my sentences short.",
            "options": [
                {"value": "yes", "label": "Yes, keep the language simple"},
                {"value": "no", "label": "No, normal academic English is fine"},
            ],
        },
    ]


def _pick(pool: list[dict[str, Any]], difficulty: int, used: set[str],
          rng: random.Random) -> dict[str, Any] | None:
    """Nearest-difficulty unused item, preferring an untested skill."""
    remaining = [i for i in pool if i["id"] not in used]
    if not remaining:
        return None
    remaining.sort(key=lambda i: (abs(int(i.get("difficulty", 3)) - difficulty),
                                  rng.random()))
    return remaining[0]


def start(record: dict[str, Any], pool: list[dict[str, Any]], limit: int) -> dict[str, Any]:
    record["placement"] = {
        "completed": False,
        "asked": [],
        "responses": [],
        "difficulty": START_DIFFICULTY,
        "limit": min(limit, len(pool)),
        "started": True,
    }
    return record["placement"]


def next_item(record: dict[str, Any], pool: list[dict[str, Any]]) -> dict[str, Any] | None:
    state = record.get("placement", {})
    if not state.get("started") or state.get("completed"):
        return None
    if len(state["asked"]) >= state["limit"]:
        return None
    rng = random.Random(f"{record['id']}:{len(state['asked'])}")
    item = _pick(pool, state.get("difficulty", START_DIFFICULTY), set(state["asked"]), rng)
    if item is None:
        return None
    state["asked"].append(item["id"])
    return {
        "id": item["id"],
        "pack_id": item.get("pack_id"),
        "skill": item.get("skill"),
        "difficulty": item.get("difficulty", 3),
        "type": item.get("type", "mcq"),
        "prompt": item["prompt"],
        "options": item.get("options"),
        "asked": len(state["asked"]),
        "total": state["limit"],
    }


def answer(record: dict[str, Any], pool: list[dict[str, Any]], item_id: str,
           response: Any) -> dict[str, Any]:
    state = record["placement"]
    item = next((i for i in pool if i["id"] == item_id), None)
    if item is None:
        raise KeyError(item_id)

    result = grade(item, response)
    difficulty = int(item.get("difficulty", 3))
    profile_mod.observe(record, item.get("skill", ""), result["correct"], difficulty)
    state["responses"].append({
        "item": item_id, "skill": item.get("skill"),
        "difficulty": difficulty, "correct": result["correct"],
    })
    state["difficulty"] = max(1, min(5, difficulty + (1 if result["correct"] else -1)))

    done = len(state["asked"]) >= state["limit"]
    # During placement the student is being measured, not taught, so no
    # explanation is given yet - it would contaminate later items on the same
    # skill. They get the full breakdown at the end.
    return {"correct": result["correct"], "done": done, "asked": len(state["asked"]),
            "total": state["limit"]}


def finish(record: dict[str, Any], preferences: dict[str, str],
           pool: list[dict[str, Any]]) -> dict[str, Any]:
    prefs = record.setdefault("preferences", {})
    if "language" in preferences:
        prefs["language"] = preferences["language"]
    if "voice" in preferences:
        prefs["voice"] = preferences["voice"]
    if "pace" in preferences:
        prefs["pace"] = preferences["pace"]
    if "example_first" in preferences:
        prefs["example_first"] = preferences["example_first"] == "yes"
    if "reading_support" in preferences:
        prefs["reading_support"] = preferences["reading_support"] == "yes"

    state = record.setdefault("placement", {})
    state["completed"] = True
    state["completed_on"] = profile_mod._now()

    by_skill: dict[str, dict[str, int]] = {}
    for r in state.get("responses", []):
        s = by_skill.setdefault(r["skill"] or "unclassified", {"seen": 0, "right": 0})
        s["seen"] += 1
        s["right"] += 1 if r["correct"] else 0

    def ratio(v: dict[str, int]) -> float:
        return v["right"] / v["seen"] if v["seen"] else 0.0

    strengths = [k for k, v in by_skill.items() if v["seen"] and ratio(v) >= 0.75]
    gaps = [k for k, v in by_skill.items() if v["seen"] and ratio(v) < 0.5]
    # The middle band matters. Most students land here, and telling them the
    # test said nothing would be both discouraging and untrue.
    shaky = [k for k, v in by_skill.items()
             if v["seen"] and 0.5 <= ratio(v) < 0.75]

    summary = {
        "answered": len(state.get("responses", [])),
        "correct": sum(1 for r in state.get("responses", []) if r["correct"]),
        "by_skill": by_skill,
        "strengths": strengths,
        "shaky": shaky,
        "gaps": gaps,
        "teaching_plan": _describe_plan(prefs, strengths, shaky, gaps),
    }
    state["summary"] = summary
    profile_mod.note(record, "placement",
                     f"{summary['correct']}/{summary['answered']} correct")
    return summary


def _humanise(skill: str) -> str:
    return skill.replace("-", " ").replace("_", " ")


def _describe_plan(prefs: dict[str, Any], strengths: list[str], shaky: list[str],
                   gaps: list[str]) -> list[str]:
    """Plain-language statement of how the tutor will now behave.

    A student should be able to read why the tutor is treating them the way it
    is, and argue with it.
    """
    plan = []
    pace = prefs.get("pace", "standard")
    if pace == "scaffolded":
        plan.append("I will break each idea into small pieces and ask you a question after every one.")
    elif pace == "fast":
        plan.append("I will state each idea once, then move you straight into practice.")
    else:
        plan.append("I will explain in short pieces and check your understanding as we go.")
    plan.append(
        "I will show you a worked example before the rule."
        if prefs.get("example_first", True)
        else "I will explain the rule first, then work an example with you."
    )
    if prefs.get("reading_support"):
        plan.append("I will define technical words the first time they appear and keep sentences short.")
    if gaps:
        plan.append("We start with " + ", ".join(_humanise(g) for g in gaps)
                    + " - that is where the test found real gaps.")
    if shaky:
        plan.append("You have the basics of " + ", ".join(_humanise(s) for s in shaky)
                    + ", but not securely. I will teach those properly rather than skim them, "
                      "and check often.")
    if strengths:
        plan.append("You already showed me " + ", ".join(_humanise(s) for s in strengths)
                    + ", so I will move through those quickly and only check you still have them.")
    if not (gaps or shaky or strengths):
        plan.append("The test did not cover enough ground to place you, so I will start at the "
                    "beginning and speed up as soon as you show me you are ahead.")
    return plan
